CREATE TABLE Person
(
    person_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name   varchar(150) NOT NULL UNIQUE,
    year_of_birth int          NOT NULL
);

CREATE TABLE Book
(
    book_id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holder_id             int          REFERENCES Person (person_id) ON DELETE SET NULL,
    book_title            varchar(150) NOT NULL,
    book_author           varchar(150) NOT NULL,
    book_publication_year varchar(150) NOT NULL
);


